<?php
/**
 * Copyright © 2019 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Magmodules\Sooqr\Block\Head
 */
?>
<?php if ($block->getHeadDataEnabled()) : ?>
    <script type="text/javascript">
        var sooqrUenc = '<?= $block->escapeHtml($block->getUenc()); ?>';
        var sooqrFormKey = '<?= $block->escapeHtml($block->getFormKey()) ?>';
    </script>
<?php endif; ?>