<?php
/**
 * Copyright © 2019 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Magmodules\Sooqr\Block\Head
 */
?>
<?php if ($block->getHeadDataEnabled()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "sooqrheaddata": {
                            "component": "Magmodules_Sooqr/js/head",
                            "sooqrheaddata": {
                                "url": "<?= /* @noEscape */ $block->getUrl('sooqr/head/get'); ?>"
                            }
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>