<?php
/**
 * Copyright © 2019 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Magmodules\Sooqr\Block\Init
 */
?>
<?php if ($block->getFrontendEnabled()) : ?>
    <?php
    $sooqrOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getSooqrOptions());
    ?>
    <script type="text/javascript">
        var _wssq = _wssq || [];
        _wssq.push(['_load', {'suggest': <?= /* @noEscape */ $sooqrOptions ?>}]);
        _wssq.push(['suggest._setPosition', 'screen-middle']);
        _wssq.push(['suggest._setLocale', '<?= $block->escapeHtml($block->getSooqrLanguage()) ?>']);
        <?php if (!$block->isTrackingEnabled()) : ?>
        _wssq.push(['suggest._disableTracking']);
        <?php endif; ?>
        <?= $block->escapeHtml($block->getSooqrJavascript()) ?>
        (function () {
            var ws = document.createElement('script');
            ws.type = 'text/javascript';
            ws.async = true;
            ws.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + '<?= $block->escapeUrl($block->getSooqrScriptUri()) ?>';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ws, s);
        })();
    </script>
<?php endif; ?>