<?php
/**
 * Copyright © 2019 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Magmodules\Sooqr\Block\Init
 */
?>
<?php if ($block->getFrontendEnabled()) { ?>
    <script type="text/javascript">
        var _wssq = _wssq || [];
        _wssq.push(['_load', {'suggest': <?php echo json_encode($block->getSooqrOptions()) ?>}]);
        _wssq.push(['suggest._setPosition', 'screen-middle']);
        _wssq.push(['suggest._setLocale', '<?php echo $block->getSooqrLanguage() ?>']);
        <?php if (!$block->isTrackingEnabled()) { ?>
        _wssq.push(['suggest._disableTracking']);
        <?php } ?>
        <?php echo $block->getSooqrJavascript() ?>
        (function () {
            var ws = document.createElement('script');
            ws.type = 'text/javascript';
            ws.async = true;
            ws.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + '<?php echo $block->getSooqrScriptUri() ?>';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ws, s);
        })();
    </script>
<?php } ?>