<?php
declare(strict_types=1);
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block Magmodules\Sooqr\Block\Adminhtml\System\Sooqr\Header
 */
?>
<div class="sooqr-header">
    <img src="https://www.sooqr.com/assets/novio/img/logo.png">
    <p>The leading Site search optimization tool for your eCommerce.<br>
        The visitors who use your internal Site Search are 5X more likely to buy, do not let them down with a poor
        search experience.</p>
    <a class="docs" target="_blank"
       href="https://sooqrsearch.atlassian.net/servicedesk/customer/portals">Documentation</a>
    <a class="support" target="_blank" href="hello@sooqr.com">Support</a>
    <a class="api" target="_blank" href="https://my.sooqr.com/">Get API Details</a>
</div>
<div class="sooqr-header-developed">
    <p>Development by <a href="https://www.magmodules.eu/" target="_blank">Magmodules</a></p>
</div>
